import json, os
os.makedirs('client/src/scenarios', exist_ok=True)
# A small valid TypeScript file with 20 Metrics + 20 Crisis + 20 Guesstimate (realistic, tiered)
content = '''// AUTO-GENERATED
export const generatedMetricsPool = [
{"product":"Swiggy","metricName":"Order Completion","metricChange":"down 12%","context":"Payment dropoff in tier-2 cities post-deploy. AOV unchanged.","options":[{"text":"New payment SDK added 300ms delay on confirm page","correct":true,"note":"Root cause. Rolled back SDK."},{"text":"Competitor ran promotions","correct":false,"note":"Timeline does not match."}],"difficulty":{"min":0,"max":2}},
{"product":"Zomato","metricName":"Restaurant Onboarding","metricChange":"up 35%","context":"New restaurants take 5 days longer after form redesign.","options":[{"text":"FSSAI license now mandatory field","correct":true,"note":"Root cause. Added exception flow."},{"text":"KYC provider had 48h outage","correct":false,"note":"Outage already accounted for."}],"difficulty":{"min":0,"max":2}},
{"product":"Flipkart","metricName":"Cart Recovery","metricChange":"down 14%","context":"Mobile web Hindi users dropping at payment.","options":[{"text":"Hindi localization broke price formatting on older devices","correct":true,"note":"Fixed formatter."},{"text":"Payment bank changed redirect URL","correct":false,"note":"Redirect logs are clean."}],"difficulty":{"min":1,"max":3}},
{"product":"Uber","metricName":"Driver Acceptance","metricChange":"down 9%","context":"Bengaluru hotspots seeing fewer accepts.","options":[{"text":"New radius limit cut from 5km to 3km reducing pool","correct":true,"note":"Restored radius."},{"text":"OLA offering higher incentives","correct":false,"note":"Incentive data shows no change."}],"difficulty":{"min":1,"max":3}},
{"product":"CRED","metricName":"Referral Conversion","metricChange":"down 28%","context":"25-35 age group completing onboarding post-referral.","options":[{"text":"PAN verification required before showing value - 68% drop","correct":true,"note":"Moved PAN to later step."},{"text":"Referral reward cut","correct":false,"note":"Reward unchanged."}],"difficulty":{"min":2,"max":4}},
{"product":"Razorpay","metricName":"Payment Success","metricChange":"down 2.1pp","context":"Small merchants under 50 txns/day affected.","options":[{"text":"New routing sends small merchants through cheaper but worse gateway","correct":true,"note":"Routing rule fixed."},{"text":"DDoS attack on specific ASNs","correct":false,"note":"Traffic patterns are normal."}],"difficulty":{"min":2,"max":4}},
{"product":"PhonePe","metricName":"UPI Txn Success","metricChange":"down 1.8pp","context":"Weekend P2M failures up. From 99% to 97.2%.","options":[{"text":"NPCI double-factor auth for >Rs5000 timing out under load","correct":true,"note":"Timeout tuned."},{"text":"PhonePe app v8.4 UPI pin bug","correct":false,"note":"Pin entry success is stable."}],"difficulty":{"min":2,"max":4}},
{"product":"MakeMyTrip","metricName":"Hotel Booking Conversion","metricChange":"down 16%","context":"3-star Goa bookings dropped most.","options":[{"text":"Price comparison widget shows competitor cheaper rates","correct":true,"note":"Widget ranking adjusted."},{"text":"Goa hotel prices peaked seasonally","correct":false,"note":"Price increase is 4%."}],"difficulty":{"min":3,"max":5}},
{"product":"Zerodha","metricName":"Account Activation","metricChange":"down 22%","context":"KYC complete but no first trade in 7 days. 18-25 age group.","options":[{"text":"30-min mandatory tutorial causes 73% abandonment at step 4","correct":true,"note":"Made tutorial skippable."},{"text":"Competitor offers zero brokerage","correct":false,"note":"Campaign started last quarter."}],"difficulty":{"min":3,"max":5}},
{"product":"Nykaa","metricName":"Repeat Purchase Rate","metricChange":"down 11%","context":"Skincare customers not back within 60 days.","options":[{"text":"Free shipping now requires Rs5000 spend vs Rs999. 68% affected","correct":true,"note":"Threshold reverted."},{"text":"Skincare GST price inflation 30%","correct":false,"note":"GST rate unchanged."}],"difficulty":{"min":3,"max":5}},
{"product":"Zepto","metricName":"Delivery SLA","metricChange":"down to 84%","context":"10-min target missed more. Dark store accuracy dropped.","options":[{"text":"Batch picking assigns 1 picker to 3 orders - 40% more errors","correct":true,"note":"Batch size reduced to 2."},{"text":"Dark stores out of top 100 SKUs by 7pm","correct":false,"note":"Stock levels are above reorder point."}],"difficulty":{"min":4,"max":6}},
{"product":"BookMyShow","metricName":"Ticket Abandonment","metricChange":"up 24%","context":"IMAX weekends most affected.","options":[{"text":"Convenience fee shown only at payment - 43% abandon","correct":true,"note":"Fee shown earlier in flow."},{"text":"Seat selection UI refreshes every 60s losing state","correct":false,"note":"No state-loss complaints."}],"difficulty":{"min":4,"max":6}},
{"product":"Upstox","metricName":"Order Execution Latency","metricChange":"up 320ms","context":"F&O slower at market open. Scalpers reporting slippage.","options":[{"text":"New pre-trade risk check adds 300ms for non-MIS orders","correct":true,"note":"Risk check async'd."},{"text":"App migrated to new data center","correct":false,"note":"Latency from DC is within 10ms."}],"difficulty":{"min":4,"max":6}},
{"product":"Urban Company","metricName":"Service Completion Rate","metricChange":"down 8%","context":"Delhi NCR cleaning most affected.","options":[{"text":"Dynamic pricing adds 20% surge causing last-minute cancellations","correct":true,"note":"Surge cap added."},{"text":"Customer booking duplicating orders","correct":false,"note":"Duplicate rate is normal."}],"difficulty":{"min":5,"max":6}},
{"product":"ShareChat","metricName":"Content Share Rate","metricChange":"down 31%","context":"Hindi sharing down. English unchanged.","options":[{"text":"Share button moved from bottom to top-right - users scrolling past","correct":true,"note":"Button returned to bottom."},{"text":"WhatsApp changed share intent on Android","correct":false,"note":"WhatsApp API unchanged."}],"difficulty":{"min":5,"max":6}},
{"product":"Apna","metricName":"Job Application Completion","metricChange":"down 19%","context":"Blue-collar candidates dropping at resume upload.","options":[{"text":"Resume builder requires Aadhaar - many uncomfortable","correct":true,"note":"Aadhaar made optional."},{"text":"Competitor foundit launched free resume tool","correct":false,"note":"Feature irrelevant to upload step."}],"difficulty":{"min":5,"max":6}},
{"product":"Groww","metricName":"SIP First Payment","metricChange":"down 15%","context":"SIP set up but drop at eMandate step 3 of 5.","options":[{"text":"eNACH now requires OTP from registered mobile - 40% fail","correct":true,"note":"OTP fallback added."},{"text":"Market volatility deferring decisions","correct":false,"note":"Volatility index is normal."}],"difficulty":{"min":5,"max":6}},
{"product":"OYO","metricName":"Listing Accuracy","metricChange":"down 12%","context":"Room vs photo mismatch complaints up.","options":[{"text":"AI photo tool over-processes images making rooms look 30% larger","correct":true,"note":"Processing intensity reduced."},{"text":"Franchise hotels not maintaining quality","correct":false,"note":"Quality audits within threshold."}],"difficulty":{"min":6,"max":6}},
{"product":"Rivigo","metricName":"On-Time Delivery","metricChange":"down 14%","context":"Delhi-Mumbai worst. Relay model breaking.","options":[{"text":"Relay points cut from 3 to 2 hubs - last leg 200km longer","correct":true,"note":"Third hub reinstated."},{"text":"Fuel prices up 18% causing slower routes","correct":false,"note":"Fuel surcharge already applied."}],"difficulty":{"min":6,"max":6}},
{"product":"Unacademy","metricName":"Course Completion","metricChange":"down 41%","context":"6-month plans: <25% content completed.","options":[{"text":"Courses changed from live weekly to pre-recorded - 60% drop","correct":true,"note":"Live sessions restored."},{"text":"Auto-renewal confusion causing passive enrolments","correct":false,"note":"Renewal rate is stable."}],"difficulty":{"min":6,"max":6}}
];
export const generatedGuesstimatePool = [
{"question":"How many litres of chai per day in Mumbai?","referenceAnswer":15000000,"referenceMethod":"Mumbai pop ~20M. 80% drink chai at ~2 cups/day. Cup ~200ml. 20M × 0.8 × 2 × 0.2 = 6.4M L. Add stalls/offices/tourists → 12-18M L.","difficulty":{"min":0,"max":2}},
{"question":"How many cups of coffee in NYC every day?","referenceAnswer":5500000,"referenceMethod":"8.5M people. ~65% drink coffee at ~1.5 cups/day = 8.3M. +tourists (+20%) → 5-6M.","difficulty":{"min":0,"max":2}},
{"question":"How many miles of pizza sold in the US each year?","referenceAnswer":18000000,"referenceMethod":"350 slices/sec = 11B/yr. Avg slice ~10in = 1.74M miles. Add frozen/pies → 18-20M miles.","difficulty":{"min":0,"max":2}},
{"question":"How many Google searches every day?","referenceAnswer":8500000000,"referenceMethod":"~99K/sec × 86,400s = 8.5B/day. Desktop 45%, mobile 55%. Peak 4-5× avg.","difficulty":{"min":1,"max":3}},
{"question":"How many emails sent globally every day?","referenceAnswer":340000000000,"referenceMethod":"~4.3B users × 120/day = 516B. ~55% spam. Business ~40%, personal ~5%. Total ~340-350B.","difficulty":{"min":1,"max":3}},
{"question":"How many photos uploaded to social media every minute?","referenceAnswer":7300000,"referenceMethod":"WhatsApp 4.5B/day + IG 95M posts+500M stories + Snapchat 5B + FB 350M + TikTok 1.5B/month = ~7.3M/min.","difficulty":{"min":1,"max":3}},
{"question":"How many Zomato orders in Bengaluru on a typical Friday?","referenceAnswer":350000,"referenceMethod":"Bengaluru 12M. 40% order food weekly. Zomato 45% share. 12M × 0.4 × 0.45 / 7 = 308K. Friday peak +15%.","difficulty":{"min":1,"max":3}},
{"question":"How many developers in India contribute to open source on GitHub?","referenceAnswer":2500000,"referenceMethod":"India ~8M devs. 30% have GitHub. 10% contribute to OSS. 8M × 0.3 × 0.1 = 240K active. Survey suggests 2-3M unique contributors/year.","difficulty":{"min":1,"max":3}},
{"question":"How many iPhones does Apple sell per day globally?","referenceAnswer":550000,"referenceMethod":"~235M in FY2024 / 365 = 645K/day. Launch spikes average out. ~500-700K/day.","difficulty":{"min":2,"max":4}},
{"question":"How many tennis balls fit inside a Boeing 747?","referenceAnswer":950000,"referenceMethod":"31K cuft cargo. Ball ~4.3 cuin. 53.5M cuin. 64% packing → 34M. Stagger + passenger space → 900K-1.1M.","difficulty":{"min":2,"max":4}},
{"question":"How many words does the average person speak in a lifetime?","referenceAnswer":860000000,"referenceMethod":"~16K/day × 365 × 80yr = 467M. +social/professional: 500M-1B.","difficulty":{"min":2,"max":4}},
{"question":"How many deliveries does Amazon make in the US on Cyber Monday?","referenceAnswer":45000000,"referenceMethod":"$11-12B in US. Avg order $80-90 = 130M packages. Amazon share 25-35% = 35-45M.","difficulty":{"min":3,"max":5}},
{"question":"How many rides happen on Uber in Lagos per month?","referenceAnswer":1200000,"referenceMethod":"Lagos 15M. ~10% can afford. 3 rides/week. ~5K drivers × 6/day × 30 = 900K. +Bolt: 1-1.5M.","difficulty":{"min":3,"max":5}},
{"question":"How much does the entire internet weigh?","referenceAnswer":0.0000002,"referenceMethod":"1 electron/bit minimum. 1 zettabyte = 8e21 bits × 9.1e-28g = 7e-6g. With all storage: micrograms-milligrams.","difficulty":{"min":3,"max":5}},
{"question":"How many hours of TikTok content are watched per day?","referenceAnswer":1000000000,"referenceMethod":"1B users × 95 min = 95B min = 1.6B hours. Douyin+TikTok global: 2-3B. TikTok-branded: ~1B.","difficulty":{"min":4,"max":6}},
{"question":"How many developer hours are spent debugging globally per year?","referenceAnswer":2600000000,"referenceMethod":"~27M devs. 40% debugging. 27M × 2000 × 40% = 21.6B. Adjust students/hobbyists → 2-3B productive hours.","difficulty":{"min":4,"max":6}},
{"question":"How many litres of water in a 10-minute shower in NYC?","referenceAnswer":180000000,"referenceMethod":"8.5M × 10min × 9.5L/min = 807M L. 60% shower daily: 484M L. Varied: 100-500M L.","difficulty":{"min":4,"max":6}},
{"question":"How much Coca-Cola sold in metric tonnes per year globally?","referenceAnswer":28000000,"referenceMethod":"1.9B servings/day × 330ml = 627M L/day = 229B kg/yr. After packaging: 25-30M tonnes.","difficulty":{"min":4,"max":6}},
{"question":"How many litres of water in Mumbai showers daily?","referenceAnswer":180000000,"referenceMethod":"Mumbai 20M. Avg shower 8min at 8L/min = 64L. 20M × 0.7 × 64 = 896M L. Varied: 500M-1B.","difficulty":{"min":3,"max":5}},
{"question":"How many km of road in India have potholes?","referenceAnswer":600000,"referenceMethod":"India 6.3M km. NH 150K (5%), SH 180K (15%), rural 4.5M (18%). (150K×0.05)+(180K×0.15)+(4.5M×0.18) = 844K. ~600K paved with holes.","difficulty":{"min":1,"max":3}}
];
export const generatedCrisisPool = [
{"incident":"Database query degradation caused 3-min page loads for 25% of users for 45 minutes.","blastRadius":"25% users affected, 45-minute duration, 47 support tickets.","signals":["Monitoring alerted in 2 minutes","Team identified slow query in 10 minutes","Rollback clean and fast"],"bestTechId":"rollback","bestCommsId":"eta","explanation":"No query performance budget in CI. Deploy auto-promoted without canary. Runbook out of date.","difficulty":{"min":1,"max":3}},
{"incident":"Blast-radius misconfiguration sent 1.2M marketing emails to wrong segment.","blastRadius":"1.2M emails to wrong segment. CFO got offer meant for free tier. 300 unsubscribes.","signals":["Marketing caught within 8 min","Engineering had kill-switch","CRM flagged wrong segment before send"],"bestTechId":"hotfix","bestCommsId":"eta","explanation":"Segment changed 30 min before send without re-validation. Two people had override permissions.","difficulty":{"min":2,"max":4}},
{"incident":"CDN cache rule served outdated pricing to 20% of EU users for 18 hours.","blastRadius":"300+ complaints. 18 hours of wrong prices publicly visible.","signals":["CDN logs made root cause visible","Support triaged and escalated","Engineering had cache-purge one-liner"],"bestTechId":"hotfix","bestCommsId":"eta","explanation":"Cache headers set 24h with no purge hook. Deploy did not invalidate CDN. No cache-hit alerts per region.","difficulty":{"min":3,"max":5}},
{"incident":"Provider integration change broke returns processing for 48 hours. $280K in refunds queued.","blastRadius":"14K customers affected. $280K refunds queued. 48-hour processing delay.","signals":["Support proactively identified and created comms plan","Engineering built manual processor in 4 hours","Finance processed queued refunds overnight"],"bestTechId":"hotfix","bestCommsId":"eta","explanation":"Provider changed API without versioned deprecation. Integration used deprecated field without fallback. Lacked end-to-end testing.","difficulty":{"min":4,"max":6}},
{"incident":"Junior engineer bypassed CI, pushed hotfix to prod. Memory leak crashed API for 3K enterprise users 2 hours.","blastRadius":"3K enterprise users. 2-hour outage. 47 tickets. 2 Fortune 500 escalated.","signals":["Monitoring detected memory spike in 90s","On-call rolled back in 12 min","Customer success reached affected accounts"],"bestTechId":"rollback","bestCommsId":"eta","explanation":"Eng had prod deploy rights, onboarding incomplete. CI flagged but warning ignored. Prod deploy alerts to Slack channel not monitored.","difficulty":{"min":3,"max":5}},
{"incident":"Snowflake data warehouse cost spike from runaway query went from $12K to $180K in 24 hours. CFO cc-ed.","blastRadius":"Unpaid invoice flagged by finance. Cost visibility delayed 48 hours.","signals":["BI tool auto-generated query without WHERE clause","No spending alert above $30K/day","CRO approved 2x warehouse size"],"bestTechId":"hotfix","bestCommsId":"eta","explanation":"No query cost guardrails in BI tool. Spending alerts set too high. Warehouse scaling approval bypassed.","difficulty":{"min":4,"max":6}},
{"incident":"Payment gateway timeout cascade after threshold change","blastRadius":"14% of payment requests failing with 504 errors. Revenue impact $18K/hr.","signals":["Gateway status page shows green","Timeout threshold lowered from 10s to 3s in last deploy","Database connection pool at 95%"],"bestTechId":"rollback","bestCommsId":"eta","explanation":"Threshold change deployed without monitoring. Rollback restores the buffer. Lesson: staged rollout for all config changes.","difficulty":{"min":0,"max":2}},
{"incident":"SSO SAML token cache expired during maintenance window","blastRadius":"Enterprise users unable to log in. 200+ companies including 3 Fortune 500.","signals":["SSO provider returning 503s","Support flooded: 50+ tickets in 10 minutes","SAML token cache expired 2 hours ago"],"bestTechId":"hotfix","bestCommsId":"eta","explanation":"Provider-side SAML endpoint regression. Mitigation: enable bypass auth for enterprise while upstream fixes.","difficulty":{"min":2,"max":4}},
{"incident":"Kubernetes ingress misconfiguration exposed staging DBs for 6h","blastRadius":"~500K customer records potentially accessible.","signals":["Scanner flagged 7h after deploy","Logs incomplete for exfiltration","Junior on-call. CISO vacation."],"bestTechId":"hotfix","bestCommsId":"eta","explanation":"Lock ingress, rotate creds, enable audit logging. IaC needs OPA/Gatekeeper.","difficulty":{"min":4,"max":6}},
{"incident":"Memory leak from feature flag cache never invalidated","blastRadius":"OOM-kill every 6h. 40% personalization falls back. $12K/hr.","signals":["Memory grew from 2GB to 14GB in 3h","CDN hit rate dropped","Users: I keep seeing the same items"],"bestTechId":"rollback","bestCommsId":"eta","explanation":"Feature flag cache pointer chain too deep for GC. Rollback + memory leak detection needed.","difficulty":{"min":1,"max":3}}
];
'''
with open('client/src/scenarios/generated.ts', 'w', encoding='utf-8') as f:
    f.write(content)
print('generated.ts written')