export interface Difficulty { min: number; max: number; }
function d(min: number, max: number): Difficulty { return { min, max }; }

export interface MetricsScenario {
  product: string; metricName: string; metricChange: string; context: string;
  options: { text: string; correct: boolean; note: string }[];
  difficulty: Difficulty;
}
export interface GuesstimateScenario {
  question: string; referenceAnswer: number; referenceMethod: string;
  difficulty: Difficulty;
}
export interface PrioritizeScenario {
  stakes: string; constraint: string;
  items: { id: string; title: string; desc: string; hiddenCost: string }[];
  strongRankingLooksLike: string;
  difficulty: Difficulty;
}
export interface ProductSenseScenario {
  prompt: string; context: string;
  difficulty: Difficulty;
}
export interface ABScenario {
  variantA: { label: string; users: number; conversions: number; rate: string };
  variantB: { label: string; users: number; conversions: number; rate: string };
  pValue: string; guardrails: { metric: string; control: string; variant: string; concern: boolean; explanation?: string }[];
  correctAnswer: string; correctLabel: string; explanation: string; trap: string;
  difficulty: Difficulty;
}
export interface CrisisScenario {
  incident: string; blastRadius: string; signals: string[];
  bestTechId: string; bestCommsId: string; explanation: string;
  difficulty: Difficulty;
}
export interface NorthStarScenario {
  businessModel: string; context: string; candidates: string[]; best: string;
  gamblingRisks: string[]; strongAnswerLooksLike: string;
  difficulty: Difficulty;
}
export interface StandoffScenario {
  stakeholder: string; openingLine: string; underlyingConcern: string;
  turns: { prompt: string; options: { line: string; trustDelta: number; trulyGood: boolean }[] }[];
  finalDebrief: string;
  difficulty: Difficulty;
}
export interface InterviewScenario {
  product: string; researchGoal: string;
  transcript: { speaker: string; text: string }[];
  temptingMisreads: string; realInsight: string; strongAnswerLooksLike: string;
  difficulty: Difficulty;
}
export interface ScopeScenario {
  product: string; ask: string; engineerEstimate: string; engineerReasoning: string;
  stakes: string; strongAnswerLooksLike: string;
  difficulty: Difficulty;
}
export interface QueryScenario {
  businessQuestion: string; query: string; bugType: string;
  bugExplanation: string; whatWentUnnoticed: string; correctedQuery: string;
  difficulty: Difficulty;
}
export interface PostmortemScenario {
  incident: string; whatWentWell: string[]; whatWentWrong: string[]; actionItems: string[];
  difficulty: Difficulty;
}
export interface TrustSafetyScenario {
  issue: string; severity: string; contentCategory: string; policyCategories: string[];
  difficulty: Difficulty;
}

export const metricsPool: MetricsScenario[] = [
  { product: 'Swiggy', metricName: 'Order Completion Rate', metricChange: 'down 12%', context: 'Users add to cart but drop at payment. Drop concentrated in tier-2 cities. AOV unchanged.', options: [ { text: 'A silent deploy of a new payment SDK introduced a 300ms delay on the confirmation page', correct: true, note: 'The SDK rolled out without a gradual ramp. The 300ms delay pushed page load past the patience threshold during the critical confirmation step.' }, { text: 'Increased competition from a direct competitor running aggressive promotions', correct: false, note: 'The competitor\'s promotion is in a different market segment.' }, { text: 'A background migration caused analytics instrumentation to miss events', correct: false, note: 'Event capture rate is at 99.9%.' }, { text: 'Seasonal dip following a major holiday promotion pulled demand forward', correct: false, note: 'This decline is 3x larger than the same period last year.' } ], difficulty: d(0, 2) },
  { product: 'Notion', metricName: 'Feature Adoption Rate', metricChange: 'down 22%', context: 'New AI writing features only used by 8% of users. Power users show no change; casual users aren\'t engaging. The AI button is buried in the formatting toolbar.', options: [ { text: 'The recommendation algorithm was retrained on a dataset that downweighted high-engagement categories', correct: true, note: 'Production monitoring didn\'t flag it because click-through rates remained flat — only the downstream conversion dropped.' }, { text: 'A recent UI change to the onboarding flow increased friction for returning users', correct: false, note: 'No UI changes were deployed this period.' }, { text: 'New mobile OS privacy changes reduced tracking accuracy', correct: false, note: 'The drop is in active usage, not reported traffic.' }, { text: 'An A/B test on the pricing page was ramped to 100% of traffic', correct: false, note: 'No pricing experiments were active.' } ], difficulty: d(0, 2) },
  { product: 'Airbnb', metricName: 'Booking Conversion Rate', metricChange: 'down 9%', context: 'More users are searching but fewer are booking. The drop is steepest for stays 7+ nights. Price-filter usage is up 40%.', options: [ { text: 'A CDN config change reduced image compression quality for slower connections', correct: true, note: 'WiFi users were unaffected so internal testing missed it. Mobile data users saw 2-4s additional load time.' }, { text: 'A third-party payment provider experienced regional latency', correct: false, note: 'Payment provider uptime was 99.5%.' }, { text: 'A server-side caching bug served stale data to a subset of users', correct: false, note: 'The bug affected read speeds for a small percentage only.' }, { text: 'The email notification system sent duplicate reminders, causing users to mute notifications', correct: false, note: 'Mute rates are within normal ranges at 4.2%.' } ], difficulty: d(0, 2) },
  { product: 'Stripe', metricName: 'API Error Rate', metricChange: 'up 3x from baseline', context: 'Error rate spiked after a deploy. The spike is isolated to payments-intent creation endpoints. Volume-wise, 0.8% of requests fail (still within SLA).', options: [ { text: 'The deploy included a schema migration that locked a shard for 120ms, hitting connection timeouts', correct: true, note: 'Error rate is small in absolute terms but 3x is unacceptable for payments. Root cause was a long-running migration during peak traffic.' }, { text: 'A DDoS attack targeted the payments API', correct: false, note: 'Request volume is normal; idempotency keys show no replay behavior.' }, { text: 'A client library update introduced malformed requests', correct: false, note: 'Clients were not updated this deploy.' }, { text: 'CDN caching expired, causing origin overload', correct: false, note: 'CDN hit ratio is stable.' } ], difficulty: d(2, 4) },
  { product: 'Figma', metricName: 'File Collaboration Depth', metricChange: 'down 18%', context: 'Measures average number of co-editors per file. Since the new "view-only" link default launched, many files have fewer collaborators — but export usage is up 15%.', options: [ { text: 'View-only default reduced organic collaboration invitations', correct: true, note: 'The setting made sharing frictionless but also reduced the "let\'s work together" moment. The export bump suggests users are consuming, not collaborating.' }, { text: 'A partner integration broke, preventing embeds', correct: false, note: 'Partner integrations are operational.' }, { text: 'Seasonal decrease in team design work', correct: false, note: 'The dip started exactly on the deploy date.' }, { text: 'A caching layer delayed real-time cursors', correct: false, note: 'Cursor sync latency is within 50ms, unchanged.' } ], difficulty: d(2, 4) },
  { product: 'Slack', metricName: 'Message Send Success Rate', metricChange: 'down 1.2%', context: 'Absolute rate is still 98.8%, but the baseline is 99.9%. The dip is concentrated in APAC region. Supporting tickets are spiking.', options: [ { text: 'A routing table update in the message broker incorrectly weighted one APAC shard', correct: true, note: 'The deploy rolled out globally but only APAC traffic patterns triggered the edge case. This is a classic "worked in staging" failure.' }, { text: 'Local telecom issues in APAC countries', correct: false, note: 'Telco status is green; the issue is internal.' }, { text: 'Client app version with a retry bug', correct: false, note: 'The bug pattern doesn\'t match client retry signatures.' }, { text: 'Higher message volume from a viral integration', correct: false, note: 'Overall message volume is within 5% of forecast.' } ], difficulty: d(3, 5) },
  { product: 'Uber', metricName: 'Driver Match Rate', metricChange: 'down 8%', context: 'Percentage of ride requests matched to a driver within 60 seconds. Hotspots in downtown show bigger drops than suburbs.', options: [ { text: 'The ETA algorithm was updated to be more conservative, rejecting marginal matches', correct: true, note: 'The new model reduced false matches but increased unmatched trips. The deploy succeeded technically but hurt the metric it was meant to optimize.' }, { text: 'Drivers uninstalled the app en masse', correct: false, note: 'Driver registrations are up slightly.' }, { text: 'A local event created unusual demand patterns', correct: false, note: 'The drop persists even accounting for events.' }, { text: 'Price surge scared riders away', correct: false, note: 'Surge pricing is active the same as usual.' } ], difficulty: d(3, 5) },
  { product: 'Twitch', metricName: 'Chat Engagement Rate', metricChange: 'down 15%', context: 'Chat messages per viewer-minute dropped after a UI redesign. Streamers report fewer "vibes." Viewer count is stable.', options: [ { text: 'The redesign moved the chat input below the video player, adding friction', correct: true, note: 'Chat is a habit-driven behavior. Moving it 200px lower reduced spontaneous engagement. Streamers felt the room was dead.' }, { text: 'A new TikTok competitor launched and siphoned viewers', correct: false, note: 'Viewer count is stable; this is engagement, not attention.' }, { text: 'Chat servers were upgraded and introduced latency', correct: false, note: 'Chat latency is within 10ms of before.' }, { text: 'Streamers changed their content style', correct: false, note: 'The drop started on the deploy date, not content trends.' } ], difficulty: d(3, 5) },
  { product: 'Shopify', metricName: 'Merchant App Retention (day-14)', metricChange: 'down 11%', context: 'Merchants who install a custom app are less likely to be active 2 weeks later. The drop is among first-time merchants.', options: [ { text: 'A new app onboarding flow hides the "install" CTA behind 3 tabs', correct: true, note: 'First-time merchants couldn\'t find the install action. The flow was designed for power users who already know where to look.' }, { text: 'App store search ranking changed', correct: false, note: 'Search ranking algorithm was not updated.' }, { text: 'A bug in the app SDK caused crashes on mobile', correct: false, note: 'Crash rate is within normal bounds.' }, { text: 'Seasonal slowdown in new merchant signups', correct: false, note: 'The retention curve shifted, not the signup volume.' } ], difficulty: d(4, 6) },
  { product: 'Robinhood', metricName: 'Options Trading Volume', metricChange: 'up 6% but support tickets up 120%', context: 'Volume is up but so is user frustration. Tickets mention "locked positions" and "unexplained losses."', options: [ { text: 'A new "one-tap options" feature reduced friction but didn\'t surface the risks clearly', correct: true, note: 'The feature was optimized for conversions, not comprehension. Users opened positions they didn\'t understand.' }, { text: 'A market anomaly caused unusual trading activity across the sector', correct: false, note: 'The anomaly is present but volume within the platform still out-paces sector movement.' }, { text: 'A competitor outage pushed users to Robinhood', correct: false, note: 'Competitor was operational. This is internal behavior change.' }, { text: 'A marketing campaign targeted experienced traders', correct: false, note: 'The spike came from existing users, not new signups.' } ], difficulty: d(4, 6) },
  { product: 'Spotify', metricName: 'Premium Conversion Rate', metricChange: 'down 6%', context: 'Free-tier users listen more but upgrade less. Decline steepest in 18-24 demographic. Podcast consumption up 30%.', options: [ { text: 'The new podcast catalog redirected attention away from music, reducing perceived value of premium', correct: true, note: 'Users satisfied with free podcasts see less reason to upgrade. The shift in content mix diluted the premium value proposition.' }, { text: 'Increased competition from Apple Music\'s new pricing tier', correct: false, note: 'Apple Music\'s pricing hasn\'t changed this quarter.' }, { text: 'A recent UI redesign made the upgrade button less visible', correct: false, note: 'The upgrade button placement is unchanged.' }, { text: 'Seasonal trend — summer listening habits differ from winter', correct: false, note: 'While seasonal effects exist, this decline is larger than the same period last year.' } ], difficulty: d(1, 3) },
  { product: 'DoorDash', metricName: 'Average Order Value', metricChange: 'down 7%', context: 'Average basket size decreased. Fewer add-ons (drinks, sides). Promotional usage up 25%. New "saver" delivery option has 12% take-rate.', options: [ { text: 'The "saver" delivery option attracted price-sensitive users who order cheaper items', correct: true, note: 'The saver option appeals to budget-conscious customers who trade speed for cost, naturally lowering basket size.' }, { text: 'Restaurant menu prices increased, causing users to order less', correct: false, note: 'Menu prices are unchanged; the drop is in add-ons.' }, { text: 'A bug in the cart calculation undercharges for items', correct: false, note: 'Cart totals are accurate — users are choosing cheaper combos.' }, { text: 'Supply chain issues reduced menu availability', correct: false, note: 'Menu availability is at 98%.' } ], difficulty: d(1, 3) },
];

export const guesstimatePool: GuesstimateScenario[] = [
  { question: 'How many cups of coffee are consumed in New York City every day?', referenceAnswer: 5500000, referenceMethod: 'NYC has ~8.5M people. ~65% drink coffee at ~1.5 cups/day. That gives ~8.3M cups across 2,000+ coffee shops and home brewing. Add tourists (+20%). Total: ~5-6 million.', difficulty: d(0, 2) },
  { question: 'How many miles of pizza are sold in the US each year?', referenceAnswer: 18000000, referenceMethod: 'Americans eat ~350 slices/second = 11B slices/year. Average slice ~10 inches. 11B × 10in = ~1.74M miles. Add frozen and full pies. Total: ~18-20M miles annually.', difficulty: d(0, 2) },
  { question: 'How many photos are uploaded to social media worldwide every minute?', referenceAnswer: 7300000, referenceMethod: 'WhatsApp: 4.5B/day. Instagram: 95M posts + 500M stories/day. Snapchat: 5B/day. Facebook: 350M/day. TikTok: 1.5B/month. Total: ~7.3M/min.', difficulty: d(1, 3) },
  { question: 'How many emails are sent globally every day?', referenceAnswer: 340000000000, referenceMethod: '~4.3B email users at ~120 emails/day = 516B. ~55% spam. Business ~40%, personal ~5%. Total including automated: ~340-350B.', difficulty: d(1, 3) },
  { question: 'How many Google searches happen worldwide every day?', referenceAnswer: 8500000000, referenceMethod: '~99,000 searches/second × 86,400 seconds = 8.5B/day. Desktop ~45%, mobile ~55%. Peak hours see 4-5x average traffic.', difficulty: d(1, 3) },
  { question: 'How many words does the average person speak in a lifetime?', referenceAnswer: 860000000, referenceMethod: 'Average person speaks ~16,000 words/day × 365 days × 80 years = ~467M. Add phone calls, public speaking, social situations (+15%). Some estimates vary 500M-1B.', difficulty: d(2, 4) },
  { question: 'How many tennis balls can fit inside a Boeing 747?', referenceAnswer: 950000, referenceMethod: 'Boeing 747 cargo volume ~31,000 cu ft. Tennis ball ~4.3 cubic inches. 31,000 × 1728 = 53.5M cu in. At ~64% packing efficiency: ~34M balls. If you include passenger space and nose cone and assume staggered packing: ~900K-1.1M.', difficulty: d(2, 4) },
  { question: 'How many iPhones does Apple sell per day globally?', referenceAnswer: 550000, referenceMethod: 'Apple sold ~235M iPhones in FY2024. /365 = ~645K/day. But launches spike; average across weekends/holidays skews down. Better estimate: ~500-700K/day.', difficulty: d(2, 4) },
  { question: 'How much does the entire internet weigh?', referenceAnswer: 0.0000002, referenceMethod: 'Bit = electron state. ~1 electron per bit at minimum energy. One electron = 9.1e-28 grams. 1 zettabyte = 8e21 bits. 8e21 × 9.1e-28 = ~7e-6 grams. Some estimates go up to a few grams if you include all transistors/storage media. Order of magnitude: micrograms to milligrams.', difficulty: d(3, 5) },
  { question: 'How many deliveries does Amazon make in the US on Cyber Monday?', referenceAnswer: 45000000, referenceMethod: 'Cyber Monday ~$11-12B in US. Average order ~$80-90 = ~130M packages. Amazon share ~25-35% = ~35-45M deliveries.', difficulty: d(3, 5) },
  { question: 'How many rides happen on Uber in Lagos, Nigeria per month?', referenceAnswer: 1200000, referenceMethod: 'Lagos population ~15M. ~10% can afford regular rides. Riders take ~3 rides/week = 180/mo. Drivers: ~5K active. ~6 rides/driver/day × 30 days × 5K drivers = ~900K. Add Bolt and other apps. Total: ~1-1.5M.', difficulty: d(3, 5) },
  { question: 'How much Coca-Cola is sold in metric tonnes per year globally?', referenceAnswer: 28000000, referenceMethod: '~1.9B servings/day across all Coke products. ~330ml per serving = ~627M liters/day. Finished beverage ~1kg/L. 627M × 365 = 229B liters × 1kg/L = 229B kg. Various Coke products after dilution and packaging: ~25-30M tonnes of syrup/ingredients.', difficulty: d(4, 6) },
  { question: 'How many hours of TikTok content are watched per day?', referenceAnswer: 1000000000, referenceMethod: '1B users × 95 min/day avg = ~95B minutes/day = ~1.6B hours/day. Global TikTok + Douyin: ~2-3B hours/day. TikTok-branded property: ~1B hours.', difficulty: d(4, 6) },
  { question: 'How many developer hours are spent debugging globally per year?', referenceAnswer: 2600000000, referenceMethod: '~27M devs globally. Studies say ~30-50% of time is debugging. Take 40%. 27M × 2000 working hours × 40% = 21.6B hours. Adjust for students, hobbyists: ~2-3B "productive project" hours.', difficulty: d(4, 6) },
  { question: 'How many litres of water are used in a 10-minute shower in New York City combined across all residents?', referenceAnswer: 180000000, referenceMethod: 'NYC population ~8.5M. Assume average shower 10 min at 9.5 L/min = 95 L/person. 8.5M × 95 = ~807M L. But only 60% shower at home daily: ~484M L. Some take shorter, some longer. Order of magnitude: ~100-500M L.', difficulty: d(4, 6) },
];

export const prioritizePool: PrioritizeScenario[] = [
  { stakes: 'Quarterly board meeting in 2 weeks. CEO wants to showcase momentum.', constraint: 'Only 2 engineers available this sprint. Sales pushes enterprise feature, Legal needs GDPR, user feedback demands iOS crash fix.', items: [ { id: 'A', title: 'Fix checkout crash on iOS 18', desc: 'White screen at payment. Revenue impact: ~$40K/day.', hiddenCost: 'Requires App Store review that may delay other releases' }, { id: 'B', title: 'Dark mode support', desc: 'Top user request (12k upvotes). Engineering estimate: 8 days.', hiddenCost: 'Sets precedent for theming system' }, { id: 'C', title: 'GDPR compliance audit', desc: 'Legal requirement for EU expansion. Non-compliance penalty: €20M.', hiddenCost: 'May uncover deeper data issues requiring major rework' }, { id: 'D', title: 'API rate limiter for 3rd parties', desc: 'Enterprise customer ($500K ARR) threatening churn.', hiddenCost: 'May anger free-tier users if tightened' }, { id: 'E', title: 'Performance optimization', desc: 'P95 page load up from 1.2s to 3.8s. SEO dropping.', hiddenCost: 'Root cause may be deep infrastructure, not surface optimization' } ], strongRankingLooksLike: 'A sharp PM prioritizes revenue-impact and compliance: iOS crash ($40K/day) and GDPR (€20M risk) are non-negotiable. Performance follows. Dark mode is nice-to-have. The API rate limiter can be solved with a manual override temporarily.', difficulty: d(0, 2) },
  { stakes: 'Major investor demo in 5 days. Ship items that make the best impression.', constraint: 'Engineering at 60% capacity. Investor cares about growth metrics and technical sophistication.', items: [ { id: 'A', title: 'Launch referral program', desc: 'Projected 15% acquisition lift. Simple mechanics, viral potential.', hiddenCost: 'Referral fraud risk if not monitored' }, { id: 'B', title: 'New onboarding flow', desc: 'Current onboarding has 68% drop-off at step 3. Redesign expected to improve activation by 20%.', hiddenCost: 'Engineering estimate: 14 days — too long for demo' }, { id: 'C', title: 'Dashboard redesign', desc: 'Make the product look more enterprise-ready for the investor meeting.', hiddenCost: 'Cosmetic change that doesn\'t move core metrics' }, { id: 'D', title: 'API rate limiter for 3rd parties', desc: 'Enterprise customer ($500K ARR) threatening churn without better limits.', hiddenCost: 'May anger free-tier users if tightened' }, { id: 'E', title: 'Performance optimization', desc: 'P95 page load increased from 1.2s to 3.8s. SEO rankings dropping.', hiddenCost: 'Root cause may be deep infrastructure' } ], strongRankingLooksLike: 'For an investor demo, prioritize the referral program (growth story) and the enterprise API rate limiter (revenue protection). Dashboard redesign is fine if it\'s quick, but avoid the 14-day onboarding rebuild before the demo.', difficulty: d(1, 3) },
  { stakes: 'Post-incident review. Engineers are burnt out. Sales wants a hotfix for one loud customer. Product must decide which roadmap items to cut.', constraint: 'You have 1 senior engineer for 2 weeks. Sales protects 20% of revenue from one loud customer. Engineering wants to tackle tech debt.', items: [ { id: 'A', title: 'Hotfix support portal for loud customer', desc: 'A single $200K customer threatening churn if custom report doesn\'t ship.', hiddenCost: 'Sets precedent for custom one-offs that erode roadmap' }, { id: 'B', title: 'Tech debt sprint (DB indexing)', desc: 'DB performance degrading. Queries are 5x slower than 6 months ago.', hiddenCost: 'Delays all new feature velocity for 2 weeks' }, { id: 'C', title: 'New analytics dashboard for ops team', desc: 'Ops says current view is manual and painful. Could prevent future incidents.', hiddenCost: 'Time-consuming; impact hard to measure immediately' }, { id: 'D', title: 'Security audit addressing SOC2 gap', desc: 'Auditor flagged missing encryption at rest. Risk: enterprise deals stall.', hiddenCost: 'Requires deep changes to storage layer; engineering is already stretched' }, { id: 'E', title: 'Customer-loved bug fix (search UI)', desc: 'Top voted issue in feedback. High visibility but no revenue impact.', hiddenCost: 'Looks good on NPS but doesn\'t move the needle on retention' } ], strongRankingLooksLike: 'With limited eng capacity, the SOC2 gap and tech debt create future risk. A sharp PM might temporarily address the loud customer with a manual workaround while scheduling the DB sprint. The search UI bug has high sentiment but low strategic value.', difficulty: d(2, 4) },
  { stakes: 'Your company is entering a new vertical (healthcare). Legal wants strict compliance. Engineering says 6 months. CEO wants a landing page by end of quarter.', constraint: 'Legal, Engineering, and CEO disagree on timeline. You have 1 PM and 1 engineer (new hire).', items: [ { id: 'A', title: 'Compliance-first HIPAA-ready MVP', desc: 'Full BAA, encrypted storage, audit logs. Privacy-first architecture redesigned.', hiddenCost: '6-month timeline, no product visibility this quarter' }, { id: 'B', title: 'Waitlist + educational content', desc: 'Build a waitlist with 5 blog posts explaining our approach. Low engineering lift.', hiddenCost: 'No revenue until compliance is built' }, { id: 'C', title: 'Landing page with HIPAA disclaimer', desc: 'Get brand visibility. Clear messaging that we\'re building for healthcare.', hiddenCost: 'Misleading if not actually compliant — legal warning' }, { id: 'D', title: 'Pilot with one friendly health system', desc: 'Design a pilot with a small health system that can accept lower-bar compliance.', hiddenCost: 'Pilot success may create expectations we can\'t meet broadly' }, { id: 'E', title: 'Generic enterprise version', desc: 'Build an enterprise tier with role-based access, SSO, etc. Healthcare-ready-ish.', hiddenCost: 'Still not HIPAA — legal says this doesn\'t satisfy BAA' } ], strongRankingLooksLike: 'The CEO wants visibility; legal needs safety. The smartest play combines the waitlist (low lift, signals intent) with a structured HIPAA timeline. A pure landing page without compliance is a liability. An MVP-first approach ignores that healthcare buyers need trust signals.', difficulty: d(3, 5) },
];

export const productSensePool: ProductSenseScenario[] = [
  { prompt: 'Design a feature that helps remote teams track their daily mood and energy levels without it feeling like a chore for HR.', context: 'You are the PM for a remote-first productivity tool with 2M MAU. Your users tell you they feel disconnected from their teammates.', difficulty: d(0, 2) },
  { prompt: 'Design a way for users to discover and save recipes from Instagram Reels and TikTok videos into a cookbook app.', context: 'You are the PM for a recipe app with 5M MAU. User research shows 60% of users find recipes on social media but never save them properly.', difficulty: d(0, 2) },
  { prompt: 'Design a feature that helps ride-share passengers split fares with friends who join mid-trip.', context: 'You are the PM for a ride-share app. User feedback shows groups struggle with fare splitting at different stops.', difficulty: d(0, 2) },
  { prompt: 'Design a feature that helps parents coordinate pickups and drop-offs for their kids across multiple families.', context: 'You are the PM for a family-focused calendar app. User interviews reveal that 70% of parents rely on text chains to coordinate.', difficulty: d(0, 2) },
  { prompt: 'Design a feature that helps freelancers automatically track time across multiple projects and generate invoices.', context: 'You are the PM for a freelancer toolbox app. Freelancers say they spend 3-5 hours per week on admin tasks like time tracking and invoicing.', difficulty: d(0, 2) },
  { prompt: 'Design a feature that helps small business owners automatically calculate sales tax for cross-state sales without an accountant.', context: 'You are the PM for an e-commerce platform. Sellers complain tax compliance is their #1 pain point and 30% churn within 6 months.', difficulty: d(1, 3) },
  { prompt: 'Design a feature that helps college students find roommates by matching on sleep schedule, cleanliness, and study habits.', context: 'You are the PM for a student housing platform. Current matching is location-first, leading to 40% mismatch rate.', difficulty: d(2, 4) },
  { prompt: 'Redesign the signup flow for a B2B SaaS product to reduce activation time for enterprise admins while keeping conversion rate high.', context: 'You are the PM for a project management tool. Enterprise signup takes 14 days. Self-serve takes 2 minutes. You need both paths to thrive.', difficulty: d(2, 4) },
  { prompt: 'Design a feature that helps fitness studio owners reduce no-shows without annoying members.', context: 'You are the PM for a boutique fitness booking app. Average no-show rate is 25%, costing studios ~$200/month.', difficulty: d(2, 4) },
  { prompt: 'Build a "pause subscription" feature for a meal kit company without destroying LTV or operational planning.', context: 'You are the PM for a meal kit company. 15% of subscribers cancel every month because of travel. Pauses could reduce churn by 3-5pp.', difficulty: d(3, 5) },
  { prompt: 'Design a way for restaurant managers to inventory perishable ingredients using just a smartphone camera and a 30-second daily routine.', context: 'You are the PM for a restaurant operations platform. Inventory takes 2 hours per week per location. 60% of managers skip it due to time.', difficulty: d(3, 5) },
  { prompt: 'Design a referral program for a fintech app that balances viral growth with fraud prevention and KYC compliance.', context: 'You are the PM for a neobank with 500K users. Growth is strong but CAC doubled last quarter due to regulatory overhead.', difficulty: d(3, 5) },
  { prompt: 'Redesign the onboarding for a language-learning app to push users toward their first 7-day streak, the strongest predictor of long-term retention.', context: 'You are the PM for a Duolingo-adjacent app. Day-1 retention is 45%, day-7 is 18%. First-session users who complete 1 lesson are 3x more likely to hit day 7.', difficulty: d(4, 6) },
  { prompt: 'Add an enterprise tier to a consumer photo-sharing app without destroying community culture (no ads, no tracking).', context: 'You are the PM at a VSCO-like app. Revenue per user is dropping. Enterprise clients want brand-safe curated galleries.', difficulty: d(4, 6) },
  { prompt: 'Design a moderation-tooling product for a UGC platform that reduces reviewer fatigue without missing harmful content.', context: 'You are the PM at a TikTok-like platform. Reviewers burn out at 6 months. Current false-negative rate for hate speech is 5%.', difficulty: d(4, 6) },
  { prompt: 'Design a pricing-page experiment for an AI writing SaaS tool to segment enterprise ($10K+) from SMB buyers without a sales-assisted funnel.', context: 'You are the PM at a Jasper competitor. Self-serve conversion is 0.8%. Enterprise ACV is $18K but requires a demo. You cannot add a demo path on the pricing page.', difficulty: d(5, 6) },
  { prompt: 'Build a "workspace layer" for a Figma-like design tool that lets design systems teams publish components and force brand compliance across 500+ freelancers without slowing velocity.', context: 'You are the PM at Figma. Freelancer community values speed but brands want control. Current plugin architecture is insufficient for enterprise enforcements.', difficulty: d(5, 6) },
  { prompt: 'Design a marketplace matching layer for a B2B SaaS platform that connects procurement teams with approved vendors and auto-negotiates SLAs using AI.', context: 'You are the PM at SAP Ariba. Buyers complain RFP process takes 6 weeks. Vendors say they bid on 1 in 20 RFPs. Success = faster matching + better terms.', difficulty: d(5, 6) },
  { prompt: 'Decide whether to open a new vertical (healthcare) for a B2B project management tool that already serves 2,000 construction and retail customers.', context: 'You are the Group PM. Healthcare requires HIPAA, BAA, and sales cycle doubles. Board expects 40% growth. Engineering is at capacity.', difficulty: d(6, 6) },
  { prompt: 'Design a revenue strategy for a mature, ad-supported social network where DAU is flat, CPMs are declining, and regulators are threatening to limit ad targeting.', context: 'You are the VP Product at a Twitter/X-sized network. Ads = 85% of revenue. Subscriptions only 3%. Regulators want to limit ad tracking to first-party data only.', difficulty: d(6, 6) },
];

export const abTestPool: ABScenario[] = [
  { variantA: { label: 'Control (A)', users: 50000, conversions: 5200, rate: '10.40%' }, variantB: { label: 'Variant (B)', users: 49800, conversions: 5390, rate: '10.82%' }, pValue: '0.042', guardrails: [ { metric: 'Page load time (P95)', control: '1.2s', variant: '1.4s', concern: true, explanation: '17% slower. For a lift of only 0.42pp, the speed regression is expensive in terms of SEO and perceived performance.' }, { metric: 'Refund rate', control: '2.1%', variant: '2.0%', concern: false }, { metric: 'Error rate', control: '0.3%', variant: '0.9%', concern: true, explanation: 'Error rate tripled. This suggests the variant introduces reliability risk.' } ], correctAnswer: 'ship_guardrail', correctLabel: 'Ship with a guardrail fix first', explanation: 'The conversion lift is statistically significant (p=0.042) but the guardrail metrics tell a different story. Page load time regressed by 17% and error rate tripled. A careful PM would ship only after fixing guardrails.', trap: 'The headline conversion lift looks good, but the guardrail regressions are real.', difficulty: d(0, 2) },
  { variantA: { label: 'Control (A)', users: 120000, conversions: 9600, rate: '8.00%' }, variantB: { label: 'Variant (B)', users: 119500, conversions: 9630, rate: '8.06%' }, pValue: '0.63', guardrails: [ { metric: 'Avg. session time', control: '4.2min', variant: '4.1min', concern: false }, { metric: 'Support tickets/1000 users', control: '3.4', variant: '3.5', concern: false } ], correctAnswer: 'kill', correctLabel: 'Kill it', explanation: 'p=0.63 means there\'s a 63% chance this result is random noise. The 0.06pp lift is indistinguishable from zero. With 120K users per variant, this experiment is already well-powered. Ship nothing.', trap: 'B is technically higher, but the confidence is extremely low.', difficulty: d(1, 3) },
  { variantA: { label: 'Control (A)', users: 15000, conversions: 450, rate: '3.00%' }, variantB: { label: 'Variant (B)', users: 15100, conversions: 510, rate: '3.38%' }, pValue: '0.055', guardrails: [ { metric: 'Bounce rate', control: '28%', variant: '27%', concern: false }, { metric: 'API latency', control: '210ms', variant: '215ms', concern: false } ], correctAnswer: 'run_longer', correctLabel: 'Run it longer', explanation: 'p=0.055 is close but not significant. With 15K users, the experiment may be underpowered for this effect size. Increase sample size to 30K+ per variant. If the trend holds, you\'ll likely reach significance.', trap: 'The lift is compelling, but the confidence interval is still too wide.', difficulty: d(1, 3) },
  { variantA: { label: 'Control (A)', users: 80000, conversions: 12800, rate: '16.00%' }, variantB: { label: 'Variant (B)', users: 80200, conversions: 13090, rate: '16.32%' }, pValue: '0.038', guardrails: [ { metric: 'Revenue per user', control: '$4.10', variant: '$4.05', concern: false }, { metric: 'Add-to-cart rate', control: '34%', variant: '33%', concern: false } ], correctAnswer: 'ship', correctLabel: 'Ship it', explanation: 'Statistically significant lift (p=0.038) with no material guardrail concerns. Revenue per user dip is within normal variance. Clean ship.', trap: 'No real trap here — monitor revenue per user post-launch.', difficulty: d(1, 3) },
  { variantA: { label: 'Control (A)', users: 25000, conversions: 1250, rate: '5.00%' }, variantB: { label: 'Variant (B)', users: 24900, conversions: 1638, rate: '6.58%' }, pValue: '0.001', guardrails: [ { metric: 'Long-term retention (day-30)', control: '12%', variant: '8%', concern: true, explanation: 'The new onboarding trick boosted activation but destroyed retention. Users who took the shortcut churned faster.' }, { metric: 'Refund rate', control: '2.5%', variant: '4.8%', concern: true, explanation: 'Refunds nearly doubled. The variant attracted price-sensitive users who would not renew.' } ], correctAnswer: 'kill', correctLabel: 'Kill it', explanation: 'This is a classic "Vanity Metric" trap. The headline lift is huge and highly significant, but it came at the cost of retention and refunds. A PM must look past the primary metric when guardrails scream no.', trap: 'A huge significant lift that destroys retention and refunds is a net negative.', difficulty: d(4, 6) },
  { variantA: { label: 'Control (A)', users: 200000, conversions: 18200, rate: '9.10%' }, variantB: { label: 'Variant (B)', users: 199800, conversions: 18392, rate: '9.20%' }, pValue: '0.049', guardrails: [ { metric: 'Load time', control: '1.8s', variant: '1.9s', concern: false }, { metric: 'Cart abandonment', control: '32%', variant: '31.5%', concern: false } ], correctAnswer: 'ship', correctLabel: 'Ship it', explanation: 'Large sample, significant lift, clean guardrails. Ship and monitor. The effect size is small (0.1pp) but meaningful at scale.', trap: 'Don\'t let the small effect size make you indecisive; at 200K users, it\'s real.', difficulty: d(2, 4) },
];

export const crisisPool: CrisisScenario[] = [
  { incident: 'Checkout payment failure cascade', blastRadius: '12% of checkout traffic failing with timeout errors. Revenue impact: $15K/hr.', signals: [ 'Payment gateway status page shows green (operational)', 'Internal timeout threshold was lowered from 10s to 3s in last deploy', 'Database connection pool is at 95% utilization' ], bestTechId: 'rollback', bestCommsId: 'eta', explanation: 'The timeout change is the root cause. Reverting restores the buffer. The real failure was no staged rollout — deploy should have been monitored before 100%.', difficulty: d(0, 2) },
  { incident: 'Database replication lag breach', blastRadius: 'User-facing dashboard showing stale data (30+ min delay). Affects 60% of traffic.', signals: [ 'Schema migration added index to largest table (2.1B rows)', 'Read replicas show 28 min lag (critical: 5 min)', 'Alert was suppressed during maintenance window' ], bestTechId: 'rollback', bestCommsId: 'eta', explanation: 'Online index creation on 2.1B rows overwhelmed I/O. Pause creation. Key lesson: index ops on >500M rows should be batched.', difficulty: d(1, 3) },
  { incident: 'SSO authentication outage', blastRadius: 'Enterprise users unable to log in. 200+ companies affected including 3 Fortune 500 accounts.', signals: [ 'SSO provider returning 503s for SAML assertions', 'Support flooded: 50+ tickets in 10 minutes', 'Our SAML token cache expired 2 hours ago during routine maintenance' ], bestTechId: 'rollback', bestCommsId: 'eta', explanation: 'Provider-side SAML endpoint regression. Mitigation: enable bypass auth for enterprise while upstream fixes. Pre-configure emergency bypasses next time.', difficulty: d(2, 4) },
  { incident: 'PII leak via new sharing feature', blastRadius: 'A newly-launched "share with link" feature exposes emails of 12,000 users via SEO indexing. Legal has been notified.', signals: [ 'The "share with link" page was indexed by Google within hours of launch', 'Feature was QA\'d with internal test accounts only', ' robots.txt was not updated for the new route', 'User reports started coming in via Twitter' ], bestTechId: 'hotfix', bestCommsId: 'eta', explanation: 'Speed matters here — remove indexing fast with a noindex header + unpublish links. Also notify affected users. The lesson: any new public route needs an indexing review before launch.', difficulty: d(3, 5) },
  { incident: 'Vendor CSPM misconfiguration causes customer data exposure in logs', blastRadius: 'Support staff can see full PII in request/response logs. Regulator-mandated 72-hour notification clock started.', signals: [ 'CSPM tool flagged a misconfigured S3 bucket with logs', 'Access to logs is gated by IAM, but broad read access was granted to Support role', 'No PII redaction in place for support tools', 'Incident was self-reported by a security engineer during routine audit' ], bestTechId: 'hotfix', bestCommsId: 'eta', explanation: 'Revoke broad log access, enable redaction, notify DPO. The lesson: support tooling access should be least-privilege, and log redaction should be default.', difficulty: d(4, 6) },
];

export const northStarPool: NorthStarScenario[] = [
  { businessModel: 'A subscription-based meditation app', context: 'Freemium with premium subscriptions ($12.99/mo). Revenue drivers: subscribers and retention.', candidates: [ 'Monthly Active Users', 'Premium Subscription Revenue', 'Session Completion Rate', '7-Day Streak Rate' ], best: '7-Day Streak Rate', gamblingRisks: [ 'MAU inflates via free users who never convert', 'Revenue lags by a month', 'Session rate inflates via shorter sessions', 'Streaks can be gamed with 5-second opens' ], strongAnswerLooksLike: 'Meditation value compounds with consistency. Streak rate measures habit formation. Revenue lags; MAU is too broad.', difficulty: d(0, 2) },
  { businessModel: 'An ad-supported social video platform', context: 'Free tier with ads. Revenue from advertisers per-impression (CPM).', candidates: [ 'Daily Active Users', 'Total Watch Time', 'Ad Revenue Per 1K Views', 'Creator Payout Satisfaction' ], best: 'Total Watch Time', gamblingRisks: [ 'DAU inflates from 3-second opens', 'Watch time inflates via auto-play', 'CPM inflates via ad overload', 'Creator satisfaction influenced by overpay' ], strongAnswerLooksLike: 'Watch time determines ad inventory and engagement. Balances satisfaction with business value.', difficulty: d(0, 2) },
  { businessModel: 'A B2B project management SaaS tool', context: 'Per-seat subscription ($15/seat/mo). Teams of 5-50.', candidates: [ 'Monthly Recurring Revenue', 'Daily Active Users', 'Weekly Active Teams', 'Net Revenue Retention' ], best: 'Weekly Active Teams', gamblingRisks: [ 'Revenue boosts via discounts hurt long-term', 'DAU inflates via notifications', 'WAT harder to game but slow-moving', 'NRR lags by 12 months' ], strongAnswerLooksLike: 'In B2B SaaS, team adoption within orgs is the key lever. WAT measures expand motion directly.', difficulty: d(0, 2) },
  { businessModel: 'A food delivery marketplace', context: 'Commission-based marketplace. Revenue = 20-30% commission per order.', candidates: [ 'Gross Merchandise Volume (GMV)', 'Orders Per Active User Per Week', 'Restaurant Partner NPS', 'On-Time Delivery Rate' ], best: 'Gross Merchandise Volume (GMV)', gamblingRisks: [ 'GMV inflates via large discounts destroying margins', 'Order frequency pushed by cheap items with less commission', 'Restaurant NPS influenced by low commissions', 'Delivery rate inflated by widened estimates' ], strongAnswerLooksLike: 'In marketplaces, GMV captures health from both sides: more orders (user) and higher-value supply.', difficulty: d(1, 3) },
  { businessModel: 'A two-sided freelance marketplace (Upwork-style)', context: 'Take rate 10-20% per transaction. Free to post, paid to hire.', candidates: [ 'Gross Transaction Value', 'Freelancer $ Earned', 'Client New Hire Rate', 'Freelancer 90-day retention' ], best: 'Client New Hire Rate', gamblingRisks: [ 'GTV inflates via low-value micro tasks', 'Freelancer earnings inflates via self-hires', 'Client hire rate can be juked by fake hires', 'Freelancer retention driven by top 1% earners' ], strongAnswerLooksLike: 'The platform makes money when clients repeatedly hire freelancers. New hire rate captures that loop better than GTV.', difficulty: d(2, 4) },
  { businessModel: 'A virtual-event platform (B2B webinars + conferences)', context: 'Paid registrations + enterprise licenses. ~$50M ARR, growing 60% YoY.', candidates: [ 'Registered Attendees', 'Paid Registrations per Event', 'Average Attendee Session Duration', 'Sponsor Satisfaction' ], best: 'Paid Registrations per Event', gamblingRisks: [ 'Registered attendees inflate via promo-code abuse', 'Paid registrations drop if events are low quality', 'Session duration can be inflated by idle tabs', 'Sponsor satisfaction is lagging and vanity' ], strongAnswerLooksLike: 'In events, revenue comes from paid registrations, not signups. Sponsor satisfaction is important but lagging.', difficulty: d(2, 4) },
  { businessModel: 'A fast-growing DTC apparel brand, direct-to-consumer', context: 'Acquisition cost rising 20% YoY. Return rate 28%. LTV:CAC = 2.1.', candidates: [ 'Revenue', 'Return Rate', 'Net Promoter Score (NPS)', 'Repeat Purchase Rate (within 90 days)' ], best: 'Repeat Purchase Rate (within 90 days)', gamblingRisks: [ 'Revenue inflates via discounting + paid ads', 'Return rate is lagging; quality issues show up late', 'NPS is shallow and noisy for apparel', 'Repeat rate survives aggressive discounting better than revenue' ], strongAnswerLooksLike: 'Apparel wins on repeat purchase, not acquisition. The brand that keeps customers coming back wins in DTC.', difficulty: d(3, 5) },
  { businessModel: 'A mobile puzzle game (hyper-casual, ad-supported)', context: 'Daily active users = 5M. Ad revenue = $0.40 per DAU. In-app purchase = $0.08 per DAU.', candidates: [ 'Daily Active Users', 'Day-1 Retention', 'Ad Revenue Per DAU', 'Session Count Per DAU' ], best: 'Day-1 Retention', gamblingRisks: [ 'DAU inflated by bots/ad farms', 'Day-1 retention is the strongest predictor of 30-day revenue', 'Ad revenue per DAU is a lagging proxy for engagement', 'Session count inflated by interstitial ad loops' ], strongAnswerLooksLike: 'For hyper-casual, retention is the north star. UA is cheap; keeping players is the product challenge.', difficulty: d(3, 5) },
  { businessModel: 'A community-driven Q&A platform for professional engineers (StackOverflow for AI/ML)', context: 'Freemium with job board ads and enterprise search licenses.', candidates: [ 'Questions Posted Per Day', 'Accepted Answer Rate', 'Monthly Active Employers (job board)', 'Enterprise Search License MRR' ], best: 'Enterprise Search License MRR', gamblingRisks: [ 'Questions/day inflated by student homework', 'Accepted answer rate is 90%+ and hard to improve', 'Job board employers are noisy and seasonal', 'Enterprise license revenue is durable and sticky' ], strongAnswerLooksLike: 'This platform wins when enterprises pay for search. Community is necessary but revenue = enterprise.', difficulty: d(4, 6) },
  { businessModel: 'AI coding assistant tool (GitHub Copilot competitor)', context: 'Pro subscription $19/mo. Teams $39/user/mo. Free tier with usage caps.', candidates: [ 'Monthly Active Users', 'Lines of Code Generated', 'Teams Seats Sold', 'Developer Productivity Index (custom: tasks completed/hour)' ], best: 'Developer Productivity Index (custom)', gamblingRisks: [ 'MAU inflates via curious free users', 'Lines generated inflates via copy-paste loops', 'Teams seats sold via bottoms-up virality', 'Productivity index captures real value — hard to game' ], strongAnswerLooksLike: 'Users don\'t pay for autocomplete; they pay for shipping faster. A productivity index is the hardest metric to fake.', difficulty: d(5, 6) },
  { businessModel: 'A city-government services platform (311-style, modern)', context: 'Citizens file requests, get updates, review outcomes. Funded by municipal subscription ($/resident/year).', candidates: [ 'Citizen Requests Filed', 'Resolution Rate', 'Average Resolution Time', 'Municipality Renewal Rate' ], best: 'Municipality Renewal Rate', gamblingRisks: [ 'Requests filed inflates via spam/bots', 'Resolution rate ignores complaint complexity', 'Avg resolution time can be gamed by closing tickets early', 'Renewal rate is real revenue and real satisfaction' ], strongAnswerLooksLike: 'In B2G, renewals are everything. Filing volume is vanity; the city pays for outcomes.', difficulty: d(6, 6) },
  { businessModel: 'A climate-carbon accounting SaaS for mid-market manufacturers', context: 'Regulatory tailwinds in EU + US. Customers are compliance officers and sustainability leads.', candidates: [ 'Carbon Footprints Calculated', 'Accuracy Score of Calculations', 'Number of Manufacturing Customers', 'Regulatory Filing Adoption Rate' ], best: 'Regulatory Filing Adoption Rate', gamblingRisks: [ 'Footprints calculated can be inflated by simple onboarding', 'Accuracy score is internal and can be manipulated', 'Number of customers doesn\'t indicate stickiness', 'Filing adoption means customers actually trust the output' ], strongAnswerLooksLike: 'The product succeeds when companies actually file with the regulator. That\'s the moment of truth.', difficulty: d(6, 6) },
  { businessModel: 'A creator economy platform connecting brands to creators for sponsored content', context: '10% take rate on deals. Free for creators, brands pay per campaign.', candidates: [ 'Creator Signups', 'Brand Active Campaigns', 'Total Deal Value Processed', 'Creator Earning Diversity (Gini coefficient)' ], best: 'Total Deal Value Processed', gamblingRisks: [ 'Creator signups are easy to inflate with giveaways', 'Brand campaigns can be spammed with $1 deals', 'Deal value inflates via washed engagement', 'Earning diversity is a lagging social metric, not business' ], strongAnswerLooksLike: 'The platform wins when real money changes hands. Deal value processed is the healthiest synthetic metric.', difficulty: d(6, 6) },
  { businessModel: 'A next-gen CRM built for startups (Linear + Notion + Salesforce hybrid)', context: 'SMB-first, self-serve. Startup customers grow into enterprise. High NRR target.', candidates: [ 'Number of Contacts Imported', 'Active Opportunities Created', 'Weekly Active Seats', 'Qualified Pipeline Value Created' ], best: 'Weekly Active Seats', gamblingRisks: [ 'Contacts imported is a one-time event', 'Active opportunities can be inflated by bulk creation', 'Weekly active seats = real engagement and expansion', 'Pipeline value is luring but doesn\'t mean closing' ], strongAnswerLooksLike: 'In modern CRM, expansion is everything. Weekly active seats captures how embedded the tool is in daily workflow.', difficulty: d(5, 6) },
];

export const standoffPool: StandoffScenario[] = [
  { stakeholder: 'Raj (Engineering Lead)', openingLine: 'Look, I know the CEO wants this feature by next quarter, but my team is already underwater with the platform migration. Every new feature request makes me want to quit. You need to push back on this.', underlyingConcern: 'Raj is overworked and feels his team\'s work is undervalued. He needs to feel heard, not managed.', turns: [ { prompt: 'How do you respond to Raj?', options: [ { line: 'I hear you. Let\'s walk through your sprint load together and I\'ll push back on the timeline.', trustDelta: 15, trulyGood: true }, { line: 'The CEO really wants this. Can we scope a minimum version?', trustDelta: -5, trulyGood: false }, { line: 'Deadlines are arbitrary. I\'ll tell the CEO it\'s not happening.', trustDelta: -10, trulyGood: false } ] }, { prompt: 'Raj says: "I appreciate that, but product keeps adding scope mid-sprint."', options: [ { line: 'What if we agree on a strict scope freeze this quarter? New items go into a backlog.', trustDelta: 15, trulyGood: true }, { line: 'I\'ll personally review every requirement before it reaches your team.', trustDelta: 5, trulyGood: false }, { line: 'That\'s just how product works — we discover as we build.', trustDelta: -15, trulyGood: false } ] } ], finalDebrief: 'Raj needed a system, not a shield. The scope freeze process solves the systemic issue. Best PMs build systems that distribute pressure fairly.', difficulty: d(0, 2) },
  { stakeholder: 'Priya (VP of Sales)', openingLine: 'Our biggest deal ($2M ARR) is about to close but needs custom reporting. Engineering says 6 weeks.', underlyingConcern: 'She\'s under quarterly quota pressure and worries special requests hurt her credibility.', turns: [ { prompt: 'How do you respond to Priya?', options: [ { line: 'Let\'s understand what "custom reporting" means. Maybe there\'s an 80/20 solution.', trustDelta: 10, trulyGood: true }, { line: 'We have a strict roadmap. Your customer can wait until Q3.', trustDelta: -10, trulyGood: false }, { line: 'I\'ll talk to engineering. No promises.', trustDelta: -5, trulyGood: false } ] }, { prompt: 'Priya says: "They need pivot tables and drill-downs on 5 dimensions. Comparing us to Looker."', options: [ { line: 'That\'s standard Looker. What if we white-label Looker\'s embed while building our own?', trustDelta: 15, trulyGood: true }, { line: 'I can\'t justify 6 weeks for one customer.', trustDelta: -5, trulyGood: false }, { line: 'Fine, I\'ll override engineering — 3 weeks.', trustDelta: -10, trulyGood: false } ] } ], finalDebrief: 'Priya needed a creative path. The Looker embed gave her a solution without wrecking the roadmap.', difficulty: d(1, 3) },
  { stakeholder: 'Jordan (Principal Engineer)', openingLine: 'That PR you just approved has a race condition that will corrupt user state in production. I warned you in review but you overrode me.', underlyingConcern: 'Jordan feels their expertise is being ignored and is worried about the team\'s quality bar slipping.', turns: [ { prompt: 'How do you respond to Jordan?', options: [ { line: 'You\'re absolutely right. I should have listened. What\'s the fastest fix?', trustDelta: 20, trulyGood: true }, { line: 'It got through QA — we\'ll monitor.', trustDelta: -15, trulyGood: false }, { line: 'We needed the date. Let\'s revert if it blows up.', trustDelta: -5, trulyGood: false } ] }, { prompt: 'Jordan says: "This isn\'t the first time. The last 3 PRs I flagged had production issues."', options: [ { line: 'You\'re right — I need to change how I weigh review feedback. Let\'s codify it.', trustDelta: 15, trulyGood: true }, { line: 'Sometimes we have to trade perfection for shipping.', trustDelta: -10, trulyGood: false }, { line: 'I hear you. I\'ll try harder next time.', trustDelta: 0, trulyGood: false } ] } ], finalDebrief: 'Great PMs treat strong review pushback as a process signal, not a personality conflict. Fixing the process prevents the next fire.', difficulty: d(2, 4) },
  { stakeholder: 'Elena (CEO)', openingLine: 'I gave a keynote promise that we\'d have AI features by Q3. Engineering says it\'s impossible without hiring 5 ML engineers.', underlyingConcern: 'Elena\'s credibility is on the line externally. She needs a graceful way to deliver value without looking weak.', turns: [ { prompt: 'How do you respond?', options: [ { line: 'Let\'s define what "AI features" means. Maybe we can ship a credible v1 with off-the-shelf models.', trustDelta: 15, trulyGood: true }, { line: 'We should hire the 5 engineers. Can we rush offers?', trustDelta: 0, trulyGood: false }, { line: 'Keynotes are aspirational. I\'ll set expectations internally.', trustDelta: -10, trulyGood: false } ] }, { prompt: 'Elena says: "The press picked it up. Analysts are asking."', options: [ { line: 'We publish a roadmap: what\'s possible in Q3, what follows. Transparency buys time.', trustDelta: 15, trulyGood: true }, { line: 'Let\'s release a private beta and call it "launching."', trustDelta: -5, trulyGood: false }, { line: 'I\'ll write a blog post on our "AI direction" without specifics.', trustDelta: 5, trulyGood: false } ] } ], finalDebrief: 'Great PMs reframe promises as roadmaps. A public vision needs a public plan, not a private scramble.', difficulty: d(4, 6) },
];

export const interviewPool: InterviewScenario[] = [
  { product: 'Subscription fitness app', researchGoal: 'Understand why 7-day trial users aren\'t converting to paid subscriptions.', transcript: [ { speaker: 'interviewer', text: 'Walk me through your experience with the app this week.' }, { speaker: 'user', text: 'I liked the workouts but I didn\'t understand what I\'d get if I paid. The trial felt the same as the full version.' }, { speaker: 'interviewer', text: 'Did you see any prompts about upgrading?' }, { speaker: 'user', text: 'There was a banner on the settings page but I never go there. I just open the app, do a workout, and leave.' } ], temptingMisreads: 'Users don\'t see the value, so show more upgrade prompts.', realInsight: 'Pricing communication is in a dead zone (settings). Surface it post-workout when value is freshest.', strongAnswerLooksLike: 'Identify that pricing is in low-traffic areas and suggest high-engagement placement post-workout.', difficulty: d(0, 2) },
  { product: 'B2B SaaS dashboard', researchGoal: 'Find out why churn jumped from 3% to 8% month-over-month among mid-market customers.', transcript: [ { speaker: 'interviewer', text: 'What made you start looking for alternatives?' }, { speaker: 'user', text: 'Your new dashboard update slowed things down. It takes 3 extra clicks to do anything.' }, { speaker: 'interviewer', text: 'Did anyone on your team push back internally to keep using us?' }, { speaker: 'user', text: 'Our ops lead liked it, but finance controls budget and they only care about speed.' } ], temptingMisreads: 'The new dashboard regression is the cause. Revert it and churn will drop.', realInsight: 'The buyer changed — finance now holds budget. The product is fine; the buyer changed and dashboard speed became a convenient excuse.', strongAnswerLooksLike: 'Identify that the decision maker changed. Address finance\'s needs, not just ops\' UX.', difficulty: d(2, 4) },
  { product: 'E-commerce marketplace', researchGoal: 'Understand why sellers with <10 SKUs stopped listing new products after the new onboarding flow.', transcript: [ { speaker: 'interviewer', text: 'Walk me through listing your first product on the new flow.' }, { speaker: 'user', text: 'It asked me for 12 attributes I didn\'t have — size, material, country of origin. I sell handmade jewelry. It felt like I was applying for a bank loan.' }, { speaker: 'interviewer', text: 'Was there anything that helped?' }, { speaker: 'user', text: 'I called support. They said they\'d add a "skip for handmade" option, but it never came.' } ], temptingMisreads: 'The form is too long. Cut fields and conversions will improve.', realInsight: 'The form was designed for mass-produced goods. The real insight: category-specific onboarding. Handmade sellers need a different path.', strongAnswerLooksLike: 'Segment seller types and design category-aware onboarding. Support requests reveal demand.', difficulty: d(3, 5) },
];

export const scopePool: ScopeScenario[] = [
  { product: 'E-commerce platform', ask: 'Add a real-time inventory tracking dashboard for merchants', engineerEstimate: '6 weeks minimum', engineerReasoning: 'We need to build a new WebSocket pipeline, a caching layer, and a new dashboard UI. The inventory team is already working on the API migration.', stakes: 'Merchant churn rate increasing. Competitors launched this feature 2 months ago.', strongAnswerLooksLike: 'Question whether all merchants need real-time (maybe daily sync for small merchants). Could we use polling or SSE instead of WebSockets?', difficulty: d(1, 3) },
  { product: 'Fintech startup', ask: 'Build a bill-pay feature for SMB customers', engineerEstimate: '14 weeks', engineerReasoning: 'We need to integrate with 3 payment rails, build fraud detection, and support ACH, wire, and card. Also need compliance review.', stakes: 'SMB churn is 12% monthly. Competitors offer bill pay.', strongAnswerLooksLike: 'Given the 14-week timeline, propose a 3-phase rollout: ACH first, card second, wire later. Ship minimal but real value in 6 weeks.', difficulty: d(2, 4) },
  { product: 'Health-tech startup', ask: 'FHIR API integration for 3 hospital systems', engineerEstimate: '6 months', engineerReasoning: 'Each hospital has a different EHR vendor and custom schema. Need to build an adapter per hospital plus testing.', stakes: 'Hospital systems won\'t sign without integration. Revenue depends on enterprise deals.', strongAnswerLooksLike: 'Instead of custom adapters, propose a normalized FHIR facade that each EHR maps to once. Library of adapters becomes reusable assets.', difficulty: d(4, 6) },
  { product: 'Ed-tech platform', ask: 'Add live video tutoring to a product that currently only supports chat and forums', engineerEstimate: '8 weeks minimum', engineerReasoning: 'Need to integrate a real-time video SDK, handle scheduling, build recording infrastructure, and ensure accessibility.', stakes: 'Competitor just launched live video. Sales says 3 deals are on hold.', strongAnswerLooksLike: 'Before building, propose a concierge MVP: schedule Zoom calls manually. Measure demand before building tech. If 60%+ of waiting customers convert, invest in the real feature.', difficulty: d(3, 5) },
];

export const queryQuestPool: QueryScenario[] = [
  { businessQuestion: 'How many users signed up last week?', query: 'SELECT COUNT(*) FROM users WHERE signup_date >= NOW() - INTERVAL 7 DAY;', bugType: 'missing_filter', bugExplanation: 'The query counts all users who signed up since 7 days ago, including those who may have deleted their accounts.', whatWentUnnoticed: 'The WHERE clause only checks signup date, not account status.', correctedQuery: 'SELECT COUNT(*) FROM users WHERE signup_date >= NOW() - INTERVAL 7 DAY AND deleted_at IS NULL;', difficulty: d(0, 2) },
  { businessQuestion: 'Total revenue from subscriptions last month?', query: 'SELECT SUM(amount) FROM subscriptions WHERE MONTH(created_at) = MONTH(NOW()) AND YEAR(created_at) = YEAR(NOW());', bugType: 'logic_error', bugExplanation: 'Using MONTH() and YEAR() on created_at only captures the original signup month, not recurring revenue credits. Renewals and failed payments are missed.', whatWentUnnoticed: 'Subscriptions generate recurring transactions, not one-time sign-ups.', correctedQuery: 'SELECT SUM(amount) FROM subscription_events WHERE event_type = "charge" AND MONTH(created_at) = MONTH(NOW()) AND YEAR(created_at) = YEAR(NOW());', difficulty: d(1, 3) },
  { businessQuestion: 'How many unique users made a purchase in Q1, broken down by country?', query: 'SELECT country, COUNT(DISTINCT user_id) as users FROM orders GROUP BY country;', bugType: 'missing_join', bugExplanation: 'The orders table may not have the latest country for a user if they moved. The query uses the order\'s shipping country, not the user\'s current residence.', whatWentUnnoticed: 'User geography changes. The query also double-counts if an order has multiple line items stored separately.', correctedQuery: 'SELECT u.country, COUNT(DISTINCT o.user_id) FROM users u JOIN orders o ON u.id = o.user_id WHERE o.created_at BETWEEN ... GROUP BY u.country;', difficulty: d(2, 4) },
  { businessQuestion: 'What is the 7-day rolling average of daily active users?', query: 'SELECT AVG(dau) FROM daily_metrics WHERE date >= CURDATE() - INTERVAL 7 DAY;', bugType: 'window_function_missing', bugExplanation: 'This returns the flat average of the last 7 days, not a rolling average per day. It includes today as a partial day.', whatWentUnnoticed: 'A rolling average requires a window function and proper date handling.', correctedQuery: 'SELECT date, AVG(dau) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as rolling_7d FROM daily_metrics WHERE date >= CURDATE() - INTERVAL 7 DAY;', difficulty: d(3, 5) },
];

export const postmortemPool: PostmortemScenario[] = [
  { incident: 'Database query degradation caused 3-min page load times for 25% of users for 45 minutes.', whatWentWell: [ 'Monitoring alerted within 2 minutes', 'Team identified the slow query within 10 minutes', 'Rollback was clean and fast' ], whatWentWrong: [ 'No query performance budget in CI/CD', 'Deploy was auto-promoted without canary testing', 'Incident response runbook was out of date' ], actionItems: [ 'Add query performance regression tests to CI', 'Require manual approval for DB schema changes', 'Schedule runbook review every 2 weeks' ], difficulty: d(1, 3) },
  { incident: 'Blast-radius misconfiguration sent 1.2M marketing emails to the wrong segment (enterprise, not SMB). CFO received the offer meant for free-tier users.', whatWentWell: [ 'Marketing caught the mistake within 8 minutes and paused the campaign', 'Engineering had a kill-switch for the campaign', 'CRM flagged the wrong segment before send' ], whatWentWrong: [ 'Segment was changed 30 minutes before send but not re-validated', 'The preview was sent to the wrong list and no one noticed', 'Two people had permissions to override the segment check' ], actionItems: [ 'Require two-person approval for campaigns to >50K users', 'Automate a preview send + validation step', 'Audit permission grants quarterly' ], difficulty: d(2, 4) },
  { incident: 'A misconfigured CDN cache rule caused 20% of EU users to see outdated pricing for 18 hours. Support received 300+ complaints.', whatWentWell: [ 'CDN logs made root cause visible within hours', 'Customer support triaged complaints and escalated quickly', 'Engineering had a cache-purge one-liner' ], whatWentWrong: [ 'Cache headers were set for 24h with no purge-on-update hook', 'Deploy pipeline didn\'t invalidate CDN cache after pricing update', 'No alert was set on cache-hit ratio per region' ], actionItems: [ 'Set cache TTL ≤ 1h for pricing endpoints', 'Automate cache invalidation in deploy pipeline', 'Add cache-hit ratio alerts by region' ], difficulty: d(3, 5) },
  { incident: 'A provider integration change broke returns processing for 48 hours. $280K in refunds queued and 14K customers affected.', whatWentWell: [ 'Customer support proactively identified the issue and created a comms plan', 'Engineering built a manual returns processor within 4 hours', 'Finance processed all queued refunds manually overnight' ], whatWentWrong: [ 'Provider changed their API contract without a versioned deprecation', 'Our integration used the deprecated field without a fallback', 'We lacked end-to-end testing for the returns path' ], actionItems: [ 'Require contract notifications be routed to eng + PM', 'Add end-to-end integration tests for all payment paths', 'Build a dead-letter queue for failed refunds with ops alerts' ], difficulty: d(4, 6) },
];

export const trustSafetyPool: TrustSafetyScenario[] = [
  { issue: 'A user reported that an AI-generated response provided medical advice that could be dangerous if followed.', severity: 'high', contentCategory: 'health_advice', policyCategories: [ 'Medical advice prohibition', 'Safety-critical content', 'Expert certification requirement' ], difficulty: d(1, 3) },
  { issue: 'A political campaign paid for an ad that used AI-generated imagery depicting a real candidate in a false scenario. 400K impressions before takedown.', severity: 'high', contentCategory: 'election_integrity', policyCategories: [ 'Misinformation policy', 'Election ads restriction', 'AI disclosure requirement' ], difficulty: d(2, 4) },
  { issue: 'A user livestreamed a dangerous viral challenge. 12 copycat injuries reported within 24 hours.', severity: 'high', contentCategory: 'harmful_behavior', policyCategories: [ 'Harmful content', 'Imminent risk', 'Copycat prevention' ], difficulty: d(3, 5) },
  { issue: 'A teen user posted about depression and self-harm. Their post was flagged by a classifier, but 3 commenters replied with harmful "encouragement."', severity: 'high', contentCategory: 'self_harm', policyCategories: [ 'Self-harm policy', 'Protective intervention', 'Comment moderation' ], difficulty: d(4, 6) },
  { issue: 'A seller on your marketplace is listing products that mimic branded items with subtle differences. Brand owners are protesting but the listings contain no trademarked logos.', severity: 'medium', contentCategory: 'counterfeit', policyCategories: [ 'Counterfeit policy', 'Brand protection', 'Trade dress nuance' ], difficulty: d(3, 5) },

  { issue: "A user was doxxed - PII partially redacted by classifier but attacker used leetspeak to bypass.", severity: "high", contentCategory: "doxxing", policyCategories: ["PII protection", "Evasion detection", "Victim support escalation"], difficulty: d(4, 6) },
  { issue: "Photorealistic deepfake of a celebrity uploaded as profile pic. Celebrity filed DMCA. 50K followers.", severity: "high", contentCategory: "deepfake", policyCategories: ["Impersonation policy", "DMCA compliance", "Synthetic media disclosure"], difficulty: d(5, 6) },
  { issue: "Religious leader posts anti-LGBTQ+ content framed as theology. Local law protects religious speech. 500K shares.", severity: "high", contentCategory: "hate_speech", policyCategories: ["Hate speech policy", "Religious freedom vs harm", "Jurisdictional enforcement"], difficulty: d(5, 6) },
  { issue: "News outlet published article using docs allegedly from your admin panel. Must determine: hack or insider?", severity: "critical", contentCategory: "data_breach", policyCategories: ["Breach notification", "Insider threat investigation", "Law enforcement engagement"], difficulty: d(6, 6) },
];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function pickForPool(poolKey: string, tier: number): any {
  switch (poolKey) {
    case 'metrics': return pick(metricsPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'guesstimate': return pick(guesstimatePool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'prioritize': return pick(prioritizePool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'productSense': return pick(productSensePool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'abTest': return pick(abTestPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'crisis': return pick(crisisPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'northStar': return pick(northStarPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'standoff': return pick(standoffPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'interview': return pick(interviewPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'scope': return pick(scopePool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'queryQuest': return pick(queryQuestPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'postmortem': return pick(postmortemPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    case 'trustSafety': return pick(trustSafetyPool.filter(s => s.difficulty.min <= tier && s.difficulty.max >= tier));
    default: return pick(metricsPool);
  }
}